import type { FastifyInstance } from 'fastify';
import type { ZodTypeProvider } from 'fastify-type-provider-zod';
import { queue } from '../../connections/queue';
import z from 'zod';



export default async function ListCompletedJobs(app: FastifyInstance) {
   app
      .withTypeProvider<ZodTypeProvider>()
      .get('/jobs/completed', {
         schema: {
            summary: "List completed background jobs",
            tags: ['Jobs'],
            description: "Retrieves a historical list of background jobs that have successfully finished execution within the current event scope. Includes the input payload and the final output (return value) generated by the worker.",
         }
      }, async (request, reply) => {
         const jobsCompleted = await queue.getCompleted()

         return reply.status(200).send({ jobs: jobsCompleted })
      })
}